
services:
  discord-bot:
    build:
      context: ./src
      additional_contexts:
        sdk: ../PySDK
    env_file: .env
    command: python3 -m src.main
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./config.yaml:/app/config.yaml
      - ../PySDK:/PySDK
    depends_on:
      - redis

  celery:
    extends:
      service: discord-bot
    command: celery -A src.celery_entrypoint worker -B --concurrency=2
